[tool.yapf]
based_on_style = "google"
use_tabs = true
coalesce_brackets = true
dedent_closing_brackets = true
each_dict_entry_on_separate_line = true
indent_dictionary_value = true
indent_closing_brackets = false
split_all_top_level_comma_separated_values = true
continuation_align_style = "valign-right"
split_complex_comprehension = true
spaces_before_comment = 2
column_limit = 120

[tool.mypy]
ignore_missing_imports = true

[flake8]
exclude = ".tox,./build"
filename = "*.py"
ignore = "F401,W191,E501,E402,E701"
